# @file
# .travis.yml - Drupal 8 Travis CI Integration

language: php

php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install Drush
  - composer global require drush/drush:dev-master
  - phpenv rehash

  # Create MySQL Database
  - mysql -e 'create database drupal;'

  # Download Drupal
  - cd ..
  - drush dl drupal-8 --drupal-project-rename=drupal
  - mv invoicer drupal/profiles
  - cd drupal

  # Install libraries
  - composer install --dev
  
  # Install drupal default profile
  - drush --verbose site-install invoicer --db-url=mysql://root:@127.0.0.1/drupal --yes

# run tests
script: php core/scripts/run-tests.sh