invoicer_invoice.settings:
  type: config_object
  label: 'Invoicer Invoice config.'
  mapping:
    vat_types:
      mapping:
        value:
          type: Integer
          label: 'The vat to apply'
        value_label:
          type: string
          label: 'Text to show'